import { FIREBASE_CONFIGURED } from './firebase-config.js';
import { requireAdmin, logoutAdmin } from './admin-auth.js';
import { listTrees, treeExists, writeTree, removeTree } from './admin-firestore.js';
import { uploadMedia } from './admin-storage.js';
import { $, note, stats, render } from './admin-view.js';
import { openForm, readValues } from './admin-form.js';
import { openQr, treeUrl } from './admin-qr.js';

let user=null, trees=[], editing=null;
async function reload(){trees=await listTrees();trees.sort((a,b)=>(a.treeName||'').localeCompare(b.treeName||'','ko'));stats(trees);render(trees)}
if(!FIREBASE_CONFIGURED){note('Firebase 설정이 필요합니다. js/firebase-config.js를 확인해 주세요.','error');$('addButton').disabled=true}else{requireAdmin(async u=>{user=u;$('userLabel').textContent=u.email||'관리자';try{await reload()}catch(e){console.error(e);note('수목 목록을 불러오지 못했습니다.','error')}},e=>{console.error(e);note('관리자 권한을 확인하지 못했습니다.','error')})}

$('treeForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const id=(editing?.id||$('treeId').value.trim()).replace(/\s+/g,'-');if(!/^[A-Za-z0-9가-힣_-]{1,80}$/.test(id)){note('수목 ID는 한글/영문/숫자/하이픈/밑줄만 사용할 수 있습니다.','error');return}const imageFile=$('imageFile').files[0],audioFile=$('audioFile').files[0];if(imageFile&&imageFile.size>10*1024*1024){note('이미지는 10MB 이하만 가능합니다.','error');return}if(audioFile&&(!audioFile.name.toLowerCase().endsWith('.mp3')||audioFile.size>30*1024*1024)){note('MP3는 30MB 이하만 가능합니다.','error');return}$('saveButton').disabled=true;note('저장 중입니다.','info');try{if(!editing&&await treeExists(id))throw new Error('이미 사용 중인 수목 고유 ID입니다.');let image={url:editing?.imageUrl||'',path:editing?.imagePath||''},audio={url:editing?.audioUrl||'',path:editing?.audioPath||''};if(imageFile)image=await uploadMedia(id,imageFile,'image');if(audioFile)audio=await uploadMedia(id,audioFile,'audio');await writeTree(id,{...readValues(),imageUrl:image.url,imagePath:image.path,audioUrl:audio.url,audioPath:audio.path},editing?.createdAt);$('treeModal').classList.remove('open');editing=null;await reload();note(`저장했습니다. 공개 URL: ${treeUrl(id)}`,'ok')}catch(err){console.error(err);note(err.message||'저장 실패','error')}finally{$('saveButton').disabled=false}});

$('treeGrid').addEventListener('click',async e=>{const b=e.target.closest('button[data-a]');if(!b)return;const t=trees.find(x=>x.id===b.dataset.id);if(!t)return;if(b.dataset.a==='edit'){editing=t;openForm(t)}if(b.dataset.a==='qr')openQr(t);if(b.dataset.a==='delete'&&confirm(`'${t.treeName||t.id}' 정보를 삭제할까요?`)){await removeTree(t.id);await reload();note('삭제했습니다.','ok')}});
$('addButton').onclick=()=>{editing=null;openForm()};$('closeModal').onclick=$('cancelButton').onclick=()=>{$('treeModal').classList.remove('open');editing=null};$('closeQr').onclick=()=>$('qrModal').classList.remove('open');$('openPublic').onclick=()=>window.open($('qrUrl').value,'_blank','noopener');$('copyUrl').onclick=()=>{$('qrUrl').select()};$('logoutButton').onclick=logoutAdmin;$('search').oninput=()=>render(trees);
$('imageFile').onchange=()=>{const f=$('imageFile').files[0];if(f){$('imagePreview').src=URL.createObjectURL(f);$('imagePreview').classList.remove('hidden')}};$('audioFile').onchange=()=>{const f=$('audioFile').files[0];if(f){$('audioPreview').src=URL.createObjectURL(f);$('audioPreview').classList.remove('hidden')}};